# Generated by Django 5.2.8 on 2025-11-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='searchterm',
            options={'ordering': ['-priority', 'term'], 'verbose_name': 'Termo de Busca', 'verbose_name_plural': 'Termos de Busca'},
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada do curso', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duração do curso em semestres', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, help_text='Nível do curso (ex: Graduação, Pós-graduação)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='modality',
            field=models.CharField(blank=True, help_text='Modalidade do curso (ex: Presencial, EAD)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordem de exibição'),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='priority',
            field=models.IntegerField(default=0, help_text='Prioridade na busca (maior = mais importante)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, help_text='Código do curso (ex: COENS)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Curso ativo no sistema'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Nome do curso', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='is_default',
            field=models.BooleanField(default=True, help_text='Termo padrão/ativo'),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='term',
            field=models.CharField(help_text='Termo de busca para vagas', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='searchterm',
            unique_together={('course', 'term')},
        ),
    ]
