# Generated by Django 5.2.8 on 2025-11-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(help_text='ID do usuário no WhatsApp (ex: 554199999999@c.us)', max_length=50, unique=True)),
                ('ra', models.CharField(blank=True, help_text='Registro Acadêmico', max_length=20, null=True)),
                ('utfpr_password', models.CharField(blank=True, help_text='Senha do Portal (Cuidado: Armazenamento sensível)', max_length=255, null=True)),
                ('is_authenticated_utfpr', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
