# Generated by Django 5.2.8 on 2025-11-29 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options_alter_searchterm_options_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_action",
            field=models.CharField(
                blank=True,
                help_text="Estado atual do fluxo conversacional do bot",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="selected_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_by_users",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="selected_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_by_users",
                to="courses.searchterm",
            ),
        ),
    ]
