# Generated by Django 5.2.8 on 2025-11-29 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_content', models.TextField()),
                ('message_type', models.CharField(choices=[('SENT', 'Enviada pelo Bot'), ('RECEIVED', 'Recebida do Usuário')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
