# Generated by Django 5.2.8 on 2025-11-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Erro')], help_text='Status do bot', max_length=20)),
                ('response_time', models.FloatField(blank=True, help_text='Tempo de resposta em ms', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro (se houver)', null=True)),
                ('session_status', models.CharField(default='unknown', help_text='Status da sessão WAHA', max_length=50)),
            ],
            options={
                'verbose_name': 'Verificação de Saúde do Bot',
                'verbose_name_plural': 'Verificações de Saúde do Bot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(help_text='Nome da métrica', max_length=100)),
                ('value', models.FloatField(help_text='Valor da métrica')),
                ('metadata', models.JSONField(blank=True, help_text='Metadados adicionais', null=True)),
            ],
            options={
                'verbose_name': 'Métrica do Bot',
                'verbose_name_plural': 'Métricas do Bot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='interactionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de Interação', 'verbose_name_plural': 'Logs de Interações'},
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadados adicionais da mensagem', null=True),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='session_id',
            field=models.CharField(default='default', help_text='ID da sessão WAHA', max_length=100),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='message_content',
            field=models.TextField(help_text='Conteúdo da mensagem'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['-created_at'], name='bot_interac_created_78511f_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['user', '-created_at'], name='bot_interac_user_id_765f49_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['message_type'], name='bot_interac_message_7e20f2_idx'),
        ),
        migrations.AddIndex(
            model_name='bothealthcheck',
            index=models.Index(fields=['-created_at'], name='bot_botheal_created_8ecffa_idx'),
        ),
        migrations.AddIndex(
            model_name='bothealthcheck',
            index=models.Index(fields=['status'], name='bot_botheal_status_49b4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='botmetrics',
            index=models.Index(fields=['metric_name', '-created_at'], name='bot_botmetr_metric__60be81_idx'),
        ),
    ]
