# Generated by Django 5.2.8 on 2025-11-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_bothealthcheck_botmetrics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("waha_url", models.URLField(default="http://localhost:3000")),
                (
                    "waha_api_key",
                    models.CharField(default="dev-api-key", max_length=255),
                ),
                (
                    "waha_session",
                    models.CharField(default="dev-session", max_length=100),
                ),
                (
                    "dashboard_username",
                    models.CharField(default="admin", max_length=150),
                ),
                (
                    "dashboard_password",
                    models.CharField(default="password", max_length=150),
                ),
            ],
            options={
                "verbose_name": "Configuração do Bot",
                "verbose_name_plural": "Configurações do Bot",
            },
        ),
    ]
