# Generated by Django 5.2.8 on 2025-11-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_botconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="botconfiguration",
            name="admin_password",
            field=models.CharField(default="admin", max_length=150),
        ),
        migrations.AddField(
            model_name="botconfiguration",
            name="admin_username",
            field=models.CharField(default="admin", max_length=150),
        ),
    ]
